#!/usr/bin/env python

# Copyright 2015 Canonical Ltd.
# Licensed under the AGPLv3, see LICENCE file for details.

from __future__ import unicode_literals

import sys

from jujubundlelib import cli


if __name__ == '__main__':
    sys.exit(cli.get_changeset(sys.argv[1:]))
